{
 "title": "Ledger Charts",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "get_accounts",
    "label": "Account",
    "query": "SELECT id AS \"__value\", name AS \"__text\"\nFROM account"
   }
  ]
 },
 "panels": [
  {
   "title": "Transactions",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"date\",\r\n  CASE WHEN amount < 0 THEN amount ELSE 0 END AS \"outcome\",\r\n  CASE WHEN amount > 0 THEN amount ELSE 0 END AS \"income\"\r\nFROM (\r\n  SELECT\r\n    \"date\",\r\n    SUM(amount) AS \"amount\"\r\n  FROM \"transaction\"\r\n  WHERE account_id = 1\r\n  GROUP BY \"date\"\r\n  ORDER BY \"date\" ASC\r\n) s"
    }
   ]
  },
  {
   "title": "Income/Outcome Part",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  'outcome' AS \"type\", SUM(CASE WHEN amount < 0 THEN 1 ELSE 0 END) AS \"count\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts\r\nUNION\r\nSELECT\r\n  'income' AS \"type\", SUM(CASE WHEN amount > 0 THEN 1 ELSE 0 END) AS \"count\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts\r\n"
    }
   ]
  },
  {
   "title": "Transactions Count",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', \"date\"),\r\n  COUNT(\"id\") AS \"transactions\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts\r\nGROUP BY DATE_TRUNC('month', \"date\")\r\nORDER BY DATE_TRUNC('month', \"date\")"
    }
   ]
  },
  {
   "title": "Running Balance",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \"date\",\r\n  SUM(amount) OVER (ORDER BY id) AS \"balance\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts"
    }
   ]
  },
  {
   "title": "Running Balance Grouped",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT \"date\",\r\n  SUM(amount_sum) OVER (ORDER BY \"date\") AS  \"balance\"\r\nFROM (\r\n  SELECT \"date\",\r\n    SUM(amount) AS \"amount_sum\"\r\n  FROM \"transaction\"\r\n  WHERE account_id = $get_accounts\r\n  GROUP BY \"date\"\r\n  ORDER BY \"date\" ASC\r\n) s"
    }
   ]
  }
 ]
}