{
 "title": "Ledger Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "get_accounts",
    "label": "Account",
    "query": "SELECT id AS \"__value\", name AS \"__text\"\nFROM account"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT currency\r\nFROM account\r\nWHERE id = $get_accounts"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(date) AS \"total_transactions\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts"
    }
   ]
  },
  {
   "title": "Last Transaction Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT amount, CASE WHEN amount < 0 THEN 'Outcome' ELSE 'Income' END AS \"type\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts\r\nORDER BY \"date\" DESC\r\nLIMIT 1"
    }
   ]
  },
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Outcome",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END) AS \"outcome\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts"
    }
   ]
  },
  {
   "title": "Current Balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(amount) AS \"balance\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts"
    }
   ]
  },
  {
   "title": "Total Income",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END) AS \"income\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts"
    }
   ]
  },
  {
   "title": "Total Outcome Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(CASE WHEN amount < 0 THEN 1 ELSE 0 END) AS \"total_outcome_transactions\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts"
    }
   ]
  },
  {
   "title": "Unique Transaction Dates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(DISTINCT date) AS \"unique_transaction_dates\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts"
    }
   ]
  },
  {
   "title": "Total Income Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(CASE WHEN amount > 0 THEN 1 ELSE 0 END) AS \"total_income_transactions\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "First Transaction Date",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"date\" AS \"first_transaction_date\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts\r\nORDER BY \"date\" ASC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Days of Last Transaction",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CURRENT_DATE - \"date\" AS \"days_difference\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts\r\nORDER BY \"date\" DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Last Transaction Date",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"date\" AS \"last_transaction_date\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts\r\nORDER BY \"date\" DESC\r\nLIMIT 1"
    }
   ]
  }
 ]
}