{
 "title": "Ledger Tables",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "get_accounts",
    "label": "Account",
    "query": "SELECT id AS \"__value\", name AS \"__text\"\nFROM account"
   }
  ]
 },
 "panels": [
  { "title": "Running Balance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Balance with Percent Delta",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \"date\", \"amount\", \"balance\",\r\nCASE WHEN \"previous_balance\" = 0\r\n  THEN 0\r\n  ELSE ROUND(COALESCE(100.0 * (\"balance\" - \"previous_balance\") / \"previous_balance\", 0), 2) \r\n  END AS \"delta\"\r\nFROM (\r\n  SELECT \"id\", \"date\", \"amount\", \"balance\",\r\n  LAG(\"balance\", 1, 0) OVER (ORDER BY \"id\") AS \"previous_balance\"\r\n  FROM (\r\n    SELECT \"id\", \"date\", \"amount\",\r\n      SUM(amount) OVER (ORDER BY \"id\") AS \"balance\"\r\n    FROM \"transaction\"\r\n\t  WHERE account_id = $get_accounts\r\n    ORDER BY id ASC\r\n  ) s\r\n) f"
    }
   ]
  },
  { "title": "Year Income/Outcome", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Year Income/Outcome",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE_TRUNC('year', \"date\") AS \"date\",\r\n  COUNT(\"id\") AS \"transactions\",\r\n  SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END) AS \"outcome\",\r\n  SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END) AS \"income\",\r\n  SUM(amount) AS \"sum\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts\r\nGROUP BY DATE_TRUNC('year', \"date\")\r\nORDER BY DATE_TRUNC('year', \"date\")"
    }
   ]
  },
  { "title": "Year-Month Income/Outcome", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Year-Month Income/Outcome",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE_TRUNC('month', \"date\") AS \"date\",\r\n  COUNT(\"id\") AS \"transactions\",\r\n  SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END) AS \"outcome\",\r\n  SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END) AS \"income\",\r\n  SUM(amount) AS \"sum\"\r\nFROM \"transaction\"\r\nWHERE account_id = $get_accounts\r\nGROUP BY DATE_TRUNC('month', \"date\")\r\nORDER BY DATE_TRUNC('month', \"date\")"
    }
   ]
  }
 ]
}